// Code generated by llcppg; DO NOT EDIT.

package system

import "github.com/goplus/lib/c"

// Atomic ordering for C11 / C++11's memory models.
//
// These values cannot change because they are shared with standard library
// implementations as well as with other compilers.
type AtomicOrderingCABI c.Int

const (
	AtomicOrderingCABI_relaxed AtomicOrderingCABI = 0
	AtomicOrderingCABI_consume AtomicOrderingCABI = 1
	AtomicOrderingCABI_acquire AtomicOrderingCABI = 2
	AtomicOrderingCABI_release AtomicOrderingCABI = 3
	AtomicOrderingCABI_acqRel  AtomicOrderingCABI = 4
	AtomicOrderingCABI_seqCst  AtomicOrderingCABI = 5
)

// Atomic ordering for LLVM's memory model.
//
// C++ defines ordering as a lattice. LLVM supplements this with NotAtomic and
// Unordered, which are both below the C++ orders.
//
// not_atomic-->unordered-->relaxed-->release--------------->acq_rel-->seq_cst
//                                   \-->consume-->acquire--/
type AtomicOrdering c.Uint

const (
	AtomicOrdering_NotAtomic AtomicOrdering = 0
	AtomicOrdering_Unordered AtomicOrdering = 1
	// Equivalent to C++'s relaxed.
	AtomicOrdering_Monotonic AtomicOrdering = 2
	// Consume = 3,  // Not specified yet.
	AtomicOrdering_Acquire AtomicOrdering = 4
	// Consume = 3,  // Not specified yet.
	AtomicOrdering_Release AtomicOrdering = 5
	// Consume = 3,  // Not specified yet.
	AtomicOrdering_AcquireRelease AtomicOrdering = 6
	// Consume = 3,  // Not specified yet.
	AtomicOrdering_SequentiallyConsistent AtomicOrdering = 7
	// Consume = 3,  // Not specified yet.
	AtomicOrdering_LAST AtomicOrdering = 7
)
