// Code generated by llcppg; DO NOT EDIT.

package system

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type SysCasFlag = c.Uint32T

//go:linkname SysMemoryFence C._ZN4llvm3sys11MemoryFenceEv
func SysMemoryFence()

//go:linkname SysCompareAndSwap C._ZN4llvm3sys14CompareAndSwapEPVjjj
func SysCompareAndSwap(ptr *SysCasFlag, new_value SysCasFlag, old_value SysCasFlag) SysCasFlag
